name: smallgreendoor
favicon: null
layout_spectrum: 0.005259106634184718
typography_spectrum: 0.8366087875328958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#a5a5a5'
    - '#838383'
    - '#4f4f4f'
    - '#272727'
  brandStrength: 0.7845468937885016
  lightness: 0.5926986271515489
  saturation: 0.5453414283692837
  rhythmicContrast: 0.5325945899821818
purpose: []
